#cloud-config
coreos:
  update:
    reboot-strategy: "off"
  units:
    - name: "docker.service"
      command: "start"
    - name: "kubelet.service"
      command: "start"
    - name: "etcd3-register-server.service"
      command: "start"
    - name: "etcd3-register-client.service"
      command: "start"
    - name: "etcd3-dns-check-then-activate.service"
      command: "start"
write_files:
  - path: "/etc/systemd/system/kubelet.service"
    permissions: "0644"
    owner: "root"
    encoding: "gzip+base64"
    content: "KUBELET_SERVICE_TEMPLATED"
  - path: "/etc/systemd/system/etcd3-register-client.service"
    permissions: "0644"
    owner: "root"
    encoding: "gzip+base64"
    content: "ETCD3_REGISTER_CLIENT_SERVICE_TEMPLATED"
  - path: "/etc/systemd/system/etcd3-register-server.service"
    permissions: "0644"
    owner: "root"
    encoding: "gzip+base64"
    content: "ETCD3_REGISTER_SERVER_SERVICE_TEMPLATED"
  - path: "/etc/systemd/system/etcd3-dns-check-then-activate.service"
    permissions: "0644"
    owner: "root"
    encoding: "gzip+base64"
    content: "ETCD3_DNS_CHECK_THEN_ACTIVATE_TEMPLATED"
  - path: "/etc/kubernetes/kubeconfig"
    permissions: "0644"
    owner: "root"
    encoding: "gzip+base64"
    content: "KUBECONFIG_TEMPLATED"
  - path: "/etc/kubernetes/pods/consul-agent.yaml"
    permissions: "0644"
    owner: "root"
    encoding: "gzip+base64"
    content: "CONSUL_AGENT_TEMPLATED"
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: "root"
    content: |
      nameserver CONSUL_SERVER
  - path: "/etc/kubernetes/staged/etcd3.yaml"
    permissions: "0644"
    owner: "root"
    content: |
      # Adapted from https://github.com/kelseyhightower/etcd-pod-gen
      apiVersion: v1
      kind: Pod
      metadata:
        name: etcd
      spec:
        hostNetwork: true
        containers:
          - name: "etcd"
            image: "quay.io/coreos/etcd:v3.1.3"
            args:
              - "etcd"
              - "--name=$private_ipv4"
              - "--discovery-srv=ETCD3_CONSUL_SERVICE"
              - "--initial-advertise-peer-urls=http://$private_ipv4:2380"
              - "--initial-cluster-token=ETCD3_INITIAL_CLUSTER_TOKEN"
              - "--initial-cluster-state=new"
              - "--advertise-client-urls=http://$private_ipv4:2379"
              - "--listen-client-urls=http://$private_ipv4:2379"
              - "--listen-peer-urls=http://$private_ipv4:2380"
              - "--election-timeout=1000"
              - "--heartbeat-interval=100"
              - "--snapshot-count=10000"
              - "--max-snapshots=5"
              - "--max-wals=5"
            ports:
              - name: client
                containerPort: 2379
                protocol: "TCP"
              - name: peer
                containerPort: 2380
                protocol: "TCP"
  - path: "/etc/consul/config.json"
    permissions: "0644"
    owner: "root"
    content: |
      {
        "data_dir": "/opt/consul",
        "log_level": "INFO",
        "client_addr": "$private_ipv4",
        "advertise_addr": "$private_ipv4",
        "bind_addr": "$private_ipv4",
        "node_name": "$private_ipv4"
      }
